import os
import re
from datetime import datetime, timedelta

from .config import AnalysisConfig
from .extract_frames import extract_frames, get_video_duration
from .frame_analyzer import create_frame_analyzer
from .models import AnalysisResult


def run_analysis(video_path, log_path, analyzer_type=None, model=None,
                 extra_flags=None, output_path=None,
                 frame_analyzer_backend=None, frame_analyzer_model=None,
                 frames_dir=None, test_spec_path=None, mode=None,
                 inline_frames=None):
    if not os.path.exists(log_path):
        raise FileNotFoundError(f"Log not found: {log_path}")

    mode = mode or AnalysisConfig.MODE
    run_validation = mode in ("validation", "both")
    run_discovery = mode in ("discovery", "both")

    # Step 1: Extract frames (or use provided inline frames for batch mode)
    if inline_frames:
        frames = inline_frames
        video_duration = 0.0
    else:
        if not os.path.exists(video_path):
            raise FileNotFoundError(f"Video not found: {video_path}")
        interval = AnalysisConfig.FRAME_INTERVAL
        max_frames = AnalysisConfig.MAX_FRAMES
        out_frames_dir = frames_dir or AnalysisConfig.FRAME_DIR
        frames = extract_frames(video_path, out_frames_dir, interval, max_frames)
        video_duration = get_video_duration(video_path)
        _inject_frame_contexts(frames, log_path, video_duration)

    # Step 2: Describe frames using vision-based FrameAnalyzer
    spec_context = _read_spec_context(test_spec_path) if test_spec_path else ""
    fa_backend = frame_analyzer_backend or AnalysisConfig.FRAME_ANALYZER_BACKEND
    frame_analyzer = create_frame_analyzer(backend=fa_backend, model=frame_analyzer_model, spec_context=spec_context)
    frame_descriptions = frame_analyzer.describe_frames(frames)

    # Step 3: Summarize log
    from .opencode_analyzer import OpencodeAnalyzer
    text_analyzer = OpencodeAnalyzer(model=model, extra_flags=extra_flags)
    log_summary = text_analyzer._summarize_log(log_path)

    result = None
    if run_validation:
        result = text_analyzer.analyze(
            video_path, log_path, frames,
            log_summary=log_summary,
            frame_descriptions=frame_descriptions,
        )

    if run_discovery:
        from .discovery_analyzer import DiscoveryAnalyzer
        ux_model = AnalysisConfig.UX_MODEL or None
        disc = DiscoveryAnalyzer(model=model, extra_flags=extra_flags, ux_model=ux_model)
        disc_result = disc.analyze(
            video_path, log_path, frames,
            log_summary=log_summary,
            frame_descriptions=frame_descriptions,
            spec_context=spec_context,
        )
        if result:
            disc_result.overall_assessment = (
                result.overall_assessment
                + "\n\n---\n# Discovery Analysis\n"
                + disc_result.overall_assessment
            )
            disc_result.pass_fail = result.pass_fail
            disc_result.errors_found = result.errors_found
            disc_result.analyzer_used = f"{result.analyzer_used}+discovery"
        result = disc_result

    if output_path:
        report_path = output_path
    elif frames_dir:
        report_path = os.path.join(os.path.dirname(frames_dir), "analysis.md")
    else:
        name = os.path.splitext(os.path.basename(video_path))[0]
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        report_path = os.path.join(AnalysisConfig.REPORT_DIR, f"{name}_{ts}_analysis.md")

    _save_report(result, report_path)
    result.report_path = report_path

    _print_summary(result)
    return result


def _save_report(result, path):
    lines = [
        "# E2E Test Analysis",
        "",
        "## Test Info",
        f"- **Suite**: {result.test_suite}",
        f"- **Case**: {result.test_case}",
        f"- **Timestamp**: {result.test_timestamp}",
        f"- **Duration**: {result.duration_seconds:.1f}s",
        f"- **Status**: {result.pass_fail}",
        f"- **Analyzer**: {result.analyzer_used}",
        f"- **Frames**: {result.frames_analyzed}",
        "",
        "## Log Summary",
        "```",
        result.log_summary,
        "```",
        "",
        "## Errors Found",
    ]
    if result.errors_found:
        for e in result.errors_found:
            lines.extend(["", f"- {e}"])
    else:
        lines.append("None")

    lines.extend([
        "",
        "## Overall Assessment",
        result.overall_assessment,
        "",
    ])

    if result.recommendations:
        lines.extend(["## Recommendations", ""])
        for r in result.recommendations:
            lines.append(f"- {r}")

    lines.extend([
        "",
        "---",
        f"*Generated by {result.analyzer_used} analyzer*",
    ])

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines))


def _read_spec_context(spec_path):
    with open(spec_path) as f:
        source = f.read()
    return f"This test is defined in {os.path.basename(spec_path)}:\n\n```python\n{source}\n```"


def _parse_log_timestamps(log_path):
    pattern = r"\[(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\]"
    entries = []
    with open(log_path) as f:
        for line in f:
            m = re.match(pattern, line)
            if m:
                ts = datetime.strptime(m.group(1), "%Y-%m-%d %H:%M:%S")
                entries.append((ts, line.rstrip()))
    return entries


def _inject_frame_contexts(frames, log_path, video_duration):
    entries = _parse_log_timestamps(log_path)
    if not entries or video_duration <= 0:
        return

    log_start = entries[0][0]
    for frame in frames:
        target = log_start + timedelta(seconds=frame.timestamp_seconds)
        window = [
            line for ts, line in entries
            if abs((ts - target).total_seconds()) <= 5
        ]
        before = [
            line for ts, line in entries
            if -10 <= (ts - target).total_seconds() < -5
        ]
        context_lines = before[-3:] + window if before else window
        if context_lines:
            frame.context = "\n".join(context_lines)


def _print_summary(result):
    print(f"\n{'=' * 56}")
    print(f"  E2E Analysis Report")
    print(f"{'=' * 56}")
    print(f"  Suite  : {result.test_suite}")
    print(f"  Case   : {result.test_case}")
    print(f"  Status : {result.pass_fail}")
    print(f"  Frames : {result.frames_analyzed}")
    print(f"  Errors : {len(result.errors_found)}")
    if result.errors_found:
        for e in result.errors_found:
            print(f"    \u2022 {e}")
    print(f"  Report : {result.report_path}")
    print(f"{'=' * 56}\n")


def run_discovery(frames, log_path, frames_dir=None, output_path=None, test_spec_path=None):
    if not frames:
        raise ValueError("No frames provided for discovery analysis")
    if not os.path.exists(log_path):
        raise FileNotFoundError(f"Log not found: {log_path}")

    spec_context = _read_spec_context(test_spec_path) if test_spec_path else ""

    fa_backend = AnalysisConfig.FRAME_ANALYZER_BACKEND
    frame_analyzer = create_frame_analyzer(backend=fa_backend, model=None, spec_context=spec_context)
    frame_descriptions = frame_analyzer.describe_frames(frames)

    log_summary = _summarize_log(log_path)

    ux_model = AnalysisConfig.UX_MODEL or None
    from .discovery_analyzer import DiscoveryAnalyzer
    disc = DiscoveryAnalyzer(ux_model=ux_model)
    result = disc.analyze(
        video_path="", log_path=log_path, frames=frames,
        log_summary=log_summary,
        frame_descriptions=frame_descriptions,
        spec_context=spec_context,
    )

    if output_path:
        report_path = output_path
    elif frames_dir:
        report_path = os.path.join(os.path.dirname(frames_dir), "discovery.md")
    else:
        name = os.path.basename(log_path).replace(".log", "")
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        report_path = os.path.join(AnalysisConfig.REPORT_DIR, f"{name}_{ts}_discovery.md")

    _save_report(result, report_path)
    result.report_path = report_path
    _print_discovery_summary(result)
    return result


def _summarize_log(log_path):
    if not os.path.exists(log_path):
        return "(log file not found)"
    kw = ["ACTION:", "NAVIGATION:", "CLICK:", "ASSERTION", "ERROR:", "COMMAND:"]
    lines = []
    with open(log_path) as f:
        for line in f:
            s = line.strip()
            if any(k in s for k in kw):
                lines.append(s)
    return "\n".join(lines[-120:]) if lines else "(empty log)"


def _print_discovery_summary(result):
    print(f"\n{'=' * 56}")
    print(f"  Discovery Analysis")
    print(f"{'=' * 56}")
    print(f"  Suite  : {result.test_suite}")
    print(f"  Case   : {result.test_case}")
    print(f"  Frames : {result.frames_analyzed}")
    print(f"  Errors : {len(result.errors_found)}")
    if result.errors_found:
        for e in result.errors_found:
            print(f"    \u2022 {e}")
    print(f"  Report : {result.report_path}")
    print(f"{'=' * 56}\n")


async def describe_single_frame(frame_path: str, backend: str = None, model: str = None) -> str:
    """Analyze a single frame image and return a description."""
    from .frame_analyzer import create_frame_analyzer
    from .models import Frame
    import asyncio

    frame = Frame(path=frame_path, timestamp_seconds=0.0, context="")

    def _run():
        analyzer = create_frame_analyzer(backend=backend, model=model)
        descriptions = analyzer.describe_frames([frame])
        return descriptions[0] if descriptions else "No description generated."

    return await asyncio.to_thread(_run)
